name: release
on:
  push:
    branches:
      - "!**"
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.14
      - name: download tools
        run: |
          mkdir -p ~/bin
          curl -sL https://github.com/Songmu/goxz/releases/download/v0.6.0/goxz_v0.6.0_linux_amd64.tar.gz | tar zxvf - && install goxz_v0.6.0_linux_amd64/goxz ~/bin/
          curl -sL https://github.com/tcnksm/ghr/releases/download/v0.13.0/ghr_v0.13.0_linux_amd64.tar.gz | tar zxvf - && install ghr_v0.13.0_linux_amd64/ghr ~/bin/
      - name: upload
        run: |
          PATH=~/bin:$PATH make upload
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
